/*
Copyright (c) 2012, University of Texas at El Paso
All rights reserved.
Redistribution and use in source and binary forms, with or without 
modification, are permitted provided that the following conditions are met:
- Redistributions of source code must retain the above copyright notice, this 
  list of conditions and the following disclaimer.
- Redistributions in binary form must reproduce the above copyright notice, 
  this list of conditions and the following disclaimer in the documentation 
  and/or other materials provided with the distribution.
  
  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" 
  AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE 
  IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE 
  ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE 
  LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR 
  CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF 
  SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS 
  INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN 
  CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) 
  ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE 
  POSSIBILITY OF SUCH DAMAGE.
 */
package edu.utep.cybershare.ws.RDFAggregater;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.6 in JDK 6 Generated
 * source version: 2.1
 * 
 */
@WebService(name = "RDFAggregater", targetNamespace = "http://provenance.trust.utep.edu")
@XmlSeeAlso({ ObjectFactory.class })
public interface RDFAggregater {

	/**
	 * 
	 * @param in1
	 * @param in0
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(name = "out", targetNamespace = "http://provenance.trust.utep.edu")
	@RequestWrapper(localName = "addDocumentAt", targetNamespace = "http://provenance.trust.utep.edu", className = "edu.utep.cybershare.ws.AddDocumentAt")
	@ResponseWrapper(localName = "addDocumentAtResponse", targetNamespace = "http://provenance.trust.utep.edu", className = "edu.utep.cybershare.ws.AddDocumentAtResponse")
	public String addDocumentAt(
			@WebParam(name = "in0", targetNamespace = "http://provenance.trust.utep.edu") String in0,
			@WebParam(name = "in1", targetNamespace = "http://provenance.trust.utep.edu") String in1);

	/**
	 * 
	 * @param in1
	 * @param in0
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(name = "out", targetNamespace = "http://provenance.trust.utep.edu")
	@RequestWrapper(localName = "addDocument", targetNamespace = "http://provenance.trust.utep.edu", className = "edu.utep.cybershare.ws.AddDocument")
	@ResponseWrapper(localName = "addDocumentResponse", targetNamespace = "http://provenance.trust.utep.edu", className = "edu.utep.cybershare.ws.AddDocumentResponse")
	public String addDocument(
			@WebParam(name = "in0", targetNamespace = "http://provenance.trust.utep.edu") String in0,
			@WebParam(name = "in1", targetNamespace = "http://provenance.trust.utep.edu") String in1);

}
