/*
Copyright (c) 2012, University of Texas at El Paso
All rights reserved.
Redistribution and use in source and binary forms, with or without 
modification, are permitted provided that the following conditions are met:
- Redistributions of source code must retain the above copyright notice, this 
  list of conditions and the following disclaimer.
- Redistributions in binary form must reproduce the above copyright notice, 
  this list of conditions and the following disclaimer in the documentation 
  and/or other materials provided with the distribution.
  
  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" 
  AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE 
  IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE 
  ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE 
  LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR 
  CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF 
  SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS 
  INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN 
  CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) 
  ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE 
  POSSIBILITY OF SUCH DAMAGE.
 */
package edu.utep.cybershare.ws.RDFAggregater;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.6 in JDK 6 Generated
 * source version: 2.1
 * 
 */
@WebServiceClient(name = "RDFAggregater", targetNamespace = "http://provenance.trust.utep.edu", wsdlLocation = "http://trust.utep.edu:8080/provenance2/services/RDFAggregater?wsdl")
public class RDFAggregater_Service extends Service {

	private final static URL RDFAGGREGATER_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(edu.utep.cybershare.ws.RDFAggregater.RDFAggregater_Service.class
					.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = edu.utep.cybershare.ws.RDFAggregater.RDFAggregater_Service.class
					.getResource(".");
			url = new URL(baseUrl,
					"http://trust.utep.edu:8080/provenance2/services/RDFAggregater?wsdl");
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: 'http://trust.utep.edu:8080/provenance2/services/RDFAggregater?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		RDFAGGREGATER_WSDL_LOCATION = url;
	}

	public RDFAggregater_Service(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public RDFAggregater_Service() {
		super(RDFAGGREGATER_WSDL_LOCATION, new QName(
				"http://provenance.trust.utep.edu", "RDFAggregater"));
	}

	/**
	 * 
	 * @return returns RDFAggregater
	 */
	@WebEndpoint(name = "RDFAggregaterHttpPort")
	public RDFAggregater getRDFAggregaterHttpPort() {
		return super.getPort(new QName("http://provenance.trust.utep.edu",
				"RDFAggregaterHttpPort"), RDFAggregater.class);
	}

	/**
	 * 
	 * @param features
	 *            A list of {@link javax.xml.ws.WebServiceFeature} to configure
	 *            on the proxy. Supported features not in the
	 *            <code>features</code> parameter will have their default
	 *            values.
	 * @return returns RDFAggregater
	 */
	@WebEndpoint(name = "RDFAggregaterHttpPort")
	public RDFAggregater getRDFAggregaterHttpPort(WebServiceFeature... features) {
		return super.getPort(new QName("http://provenance.trust.utep.edu",
				"RDFAggregaterHttpPort"), RDFAggregater.class, features);
	}
}
