/*
Copyright (c) 2012, University of Texas at El Paso
All rights reserved.
Redistribution and use in source and binary forms, with or without 
modification, are permitted provided that the following conditions are met:
- Redistributions of source code must retain the above copyright notice, this 
  list of conditions and the following disclaimer.
- Redistributions in binary form must reproduce the above copyright notice, 
  this list of conditions and the following disclaimer in the documentation 
  and/or other materials provided with the distribution.
  
  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" 
  AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE 
  IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE 
  ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE 
  LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR 
  CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF 
  SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS 
  INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN 
  CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) 
  ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE 
  POSSIBILITY OF SUCH DAMAGE.
 */
package edu.utep.cybershare.ws.RDFStore;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.6 in JDK 6 Generated
 * source version: 2.1
 * 
 */
@WebService(name = "RDFStore", targetNamespace = "http://provenance.trust.utep.edu")
@XmlSeeAlso({ ObjectFactory.class })
public interface RDFStore {

	/**
	 * 
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(name = "out", targetNamespace = "http://provenance.trust.utep.edu")
	@RequestWrapper(localName = "getOntologies", targetNamespace = "http://provenance.trust.utep.edu", className = "edu.utep.cybershare.ws.RDFStore.GetOntologies")
	@ResponseWrapper(localName = "getOntologiesResponse", targetNamespace = "http://provenance.trust.utep.edu", className = "edu.utep.cybershare.ws.RDFStore.GetOntologiesResponse")
	public String getOntologies();

	/**
	 * 
	 * @param in0
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(name = "out", targetNamespace = "http://provenance.trust.utep.edu")
	@RequestWrapper(localName = "getTypesInWDO", targetNamespace = "http://provenance.trust.utep.edu", className = "edu.utep.cybershare.ws.RDFStore.GetTypesInWDO")
	@ResponseWrapper(localName = "getTypesInWDOResponse", targetNamespace = "http://provenance.trust.utep.edu", className = "edu.utep.cybershare.ws.RDFStore.GetTypesInWDOResponse")
	public String getTypesInWDO(
			@WebParam(name = "in0", targetNamespace = "http://provenance.trust.utep.edu") String in0);

	/**
	 * 
	 * @param in0
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(name = "out", targetNamespace = "http://provenance.trust.utep.edu")
	@RequestWrapper(localName = "getNodeSetsForProject", targetNamespace = "http://provenance.trust.utep.edu", className = "edu.utep.cybershare.ws.RDFStore.GetNodeSetsForProject")
	@ResponseWrapper(localName = "getNodeSetsForProjectResponse", targetNamespace = "http://provenance.trust.utep.edu", className = "edu.utep.cybershare.ws.RDFStore.GetNodeSetsForProjectResponse")
	public String getNodeSetsForProject(
			@WebParam(name = "in0", targetNamespace = "http://provenance.trust.utep.edu") String in0);

	/**
	 * 
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(name = "out", targetNamespace = "http://provenance.trust.utep.edu")
	@RequestWrapper(localName = "getInferenceRules", targetNamespace = "http://provenance.trust.utep.edu", className = "edu.utep.cybershare.ws.RDFStore.GetInferenceRules")
	@ResponseWrapper(localName = "getInferenceRulesResponse", targetNamespace = "http://provenance.trust.utep.edu", className = "edu.utep.cybershare.ws.RDFStore.GetInferenceRulesResponse")
	public String getInferenceRules();

	/**
	 * 
	 * @param in0
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(name = "out", targetNamespace = "http://provenance.trust.utep.edu")
	@RequestWrapper(localName = "doQueryForFormattedText", targetNamespace = "http://provenance.trust.utep.edu", className = "edu.utep.cybershare.ws.RDFStore.DoQueryForFormattedText")
	@ResponseWrapper(localName = "doQueryForFormattedTextResponse", targetNamespace = "http://provenance.trust.utep.edu", className = "edu.utep.cybershare.ws.RDFStore.DoQueryForFormattedTextResponse")
	public String doQueryForFormattedText(
			@WebParam(name = "in0", targetNamespace = "http://provenance.trust.utep.edu") String in0);

	/**
	 * 
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(name = "out", targetNamespace = "http://provenance.trust.utep.edu")
	@RequestWrapper(localName = "getInferenceRulesWithInfo", targetNamespace = "http://provenance.trust.utep.edu", className = "edu.utep.cybershare.ws.RDFStore.GetInferenceRulesWithInfo")
	@ResponseWrapper(localName = "getInferenceRulesWithInfoResponse", targetNamespace = "http://provenance.trust.utep.edu", className = "edu.utep.cybershare.ws.RDFStore.GetInferenceRulesWithInfoResponse")
	public String getInferenceRulesWithInfo();

	/**
	 * 
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(name = "out", targetNamespace = "http://provenance.trust.utep.edu")
	@RequestWrapper(localName = "getNodeSets", targetNamespace = "http://provenance.trust.utep.edu", className = "edu.utep.cybershare.ws.RDFStore.GetNodeSets")
	@ResponseWrapper(localName = "getNodeSetsResponse", targetNamespace = "http://provenance.trust.utep.edu", className = "edu.utep.cybershare.ws.RDFStore.GetNodeSetsResponse")
	public String getNodeSets();

	/**
	 * 
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(name = "out", targetNamespace = "http://provenance.trust.utep.edu")
	@RequestWrapper(localName = "getConclusionURLs", targetNamespace = "http://provenance.trust.utep.edu", className = "edu.utep.cybershare.ws.RDFStore.GetConclusionURLs")
	@ResponseWrapper(localName = "getConclusionURLsResponse", targetNamespace = "http://provenance.trust.utep.edu", className = "edu.utep.cybershare.ws.RDFStore.GetConclusionURLsResponse")
	public String getConclusionURLs();

	/**
	 * 
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(name = "out", targetNamespace = "http://provenance.trust.utep.edu")
	@RequestWrapper(localName = "getNodeSetsAndConclusionURLs", targetNamespace = "http://provenance.trust.utep.edu", className = "edu.utep.cybershare.ws.RDFStore.GetNodeSetsAndConclusionURLs")
	@ResponseWrapper(localName = "getNodeSetsAndConclusionURLsResponse", targetNamespace = "http://provenance.trust.utep.edu", className = "edu.utep.cybershare.ws.RDFStore.GetNodeSetsAndConclusionURLsResponse")
	public String getNodeSetsAndConclusionURLs();

	/**
	 * 
	 * @param in0
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(name = "out", targetNamespace = "http://provenance.trust.utep.edu")
	@RequestWrapper(localName = "doQuery", targetNamespace = "http://provenance.trust.utep.edu", className = "edu.utep.cybershare.ws.RDFStore.DoQuery")
	@ResponseWrapper(localName = "doQueryResponse", targetNamespace = "http://provenance.trust.utep.edu", className = "edu.utep.cybershare.ws.RDFStore.DoQueryResponse")
	public String doQuery(
			@WebParam(name = "in0", targetNamespace = "http://provenance.trust.utep.edu") String in0);

	/**
	 * 
	 * @param in0
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(name = "out", targetNamespace = "http://provenance.trust.utep.edu")
	@RequestWrapper(localName = "getWDOsForProject", targetNamespace = "http://provenance.trust.utep.edu", className = "edu.utep.cybershare.ws.RDFStore.GetWDOsForProject")
	@ResponseWrapper(localName = "getWDOsForProjectResponse", targetNamespace = "http://provenance.trust.utep.edu", className = "edu.utep.cybershare.ws.RDFStore.GetWDOsForProjectResponse")
	public String getWDOsForProject(
			@WebParam(name = "in0", targetNamespace = "http://provenance.trust.utep.edu") String in0);

	/**
	 * 
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(name = "out", targetNamespace = "http://provenance.trust.utep.edu")
	@RequestWrapper(localName = "getFormats", targetNamespace = "http://provenance.trust.utep.edu", className = "edu.utep.cybershare.ws.RDFStore.GetFormats")
	@ResponseWrapper(localName = "getFormatsResponse", targetNamespace = "http://provenance.trust.utep.edu", className = "edu.utep.cybershare.ws.RDFStore.GetFormatsResponse")
	public String getFormats();

	/**
	 * 
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(name = "out", targetNamespace = "http://provenance.trust.utep.edu")
	@RequestWrapper(localName = "getInferenceEngines", targetNamespace = "http://provenance.trust.utep.edu", className = "edu.utep.cybershare.ws.RDFStore.GetInferenceEngines")
	@ResponseWrapper(localName = "getInferenceEnginesResponse", targetNamespace = "http://provenance.trust.utep.edu", className = "edu.utep.cybershare.ws.RDFStore.GetInferenceEnginesResponse")
	public String getInferenceEngines();

	/**
	 * 
	 * @param in0
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(name = "out", targetNamespace = "http://provenance.trust.utep.edu")
	@RequestWrapper(localName = "getNodeSetsAndConclusionURLsForProject", targetNamespace = "http://provenance.trust.utep.edu", className = "edu.utep.cybershare.ws.RDFStore.GetNodeSetsAndConclusionURLsForProject")
	@ResponseWrapper(localName = "getNodeSetsAndConclusionURLsForProjectResponse", targetNamespace = "http://provenance.trust.utep.edu", className = "edu.utep.cybershare.ws.RDFStore.GetNodeSetsAndConclusionURLsForProjectResponse")
	public String getNodeSetsAndConclusionURLsForProject(
			@WebParam(name = "in0", targetNamespace = "http://provenance.trust.utep.edu") String in0);

	/**
	 * 
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(name = "out", targetNamespace = "http://provenance.trust.utep.edu")
	@RequestWrapper(localName = "getDeclarativeRules", targetNamespace = "http://provenance.trust.utep.edu", className = "edu.utep.cybershare.ws.RDFStore.GetDeclarativeRules")
	@ResponseWrapper(localName = "getDeclarativeRulesResponse", targetNamespace = "http://provenance.trust.utep.edu", className = "edu.utep.cybershare.ws.RDFStore.GetDeclarativeRulesResponse")
	public String getDeclarativeRules();

	/**
	 * 
	 * @param in0
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(name = "out", targetNamespace = "http://provenance.trust.utep.edu")
	@RequestWrapper(localName = "getInferenceRulesWithInfoInWDO", targetNamespace = "http://provenance.trust.utep.edu", className = "edu.utep.cybershare.ws.RDFStore.GetInferenceRulesWithInfoInWDO")
	@ResponseWrapper(localName = "getInferenceRulesWithInfoInWDOResponse", targetNamespace = "http://provenance.trust.utep.edu", className = "edu.utep.cybershare.ws.RDFStore.GetInferenceRulesWithInfoInWDOResponse")
	public String getInferenceRulesWithInfoInWDO(
			@WebParam(name = "in0", targetNamespace = "http://provenance.trust.utep.edu") String in0);

	/**
	 * 
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(name = "out", targetNamespace = "http://provenance.trust.utep.edu")
	@RequestWrapper(localName = "getInformationSubclasses", targetNamespace = "http://provenance.trust.utep.edu", className = "edu.utep.cybershare.ws.RDFStore.GetInformationSubclasses")
	@ResponseWrapper(localName = "getInformationSubclassesResponse", targetNamespace = "http://provenance.trust.utep.edu", className = "edu.utep.cybershare.ws.RDFStore.GetInformationSubclassesResponse")
	public String getInformationSubclasses();

	/**
	 * 
	 * @return returns long
	 */
	@WebMethod
	@WebResult(name = "out", targetNamespace = "http://provenance.trust.utep.edu")
	@RequestWrapper(localName = "getStoreSize", targetNamespace = "http://provenance.trust.utep.edu", className = "edu.utep.cybershare.ws.RDFStore.GetStoreSize")
	@ResponseWrapper(localName = "getStoreSizeResponse", targetNamespace = "http://provenance.trust.utep.edu", className = "edu.utep.cybershare.ws.RDFStore.GetStoreSizeResponse")
	public long getStoreSize();

}
